const presetPatterns = {
  Robots: {
    step00: { "toneName": "d", "octave": "3" },
    step01: { "toneName": "d", "octave": "3" },
    step02: { "toneName": "c", "octave": "3" },
    step03: { "toneName": "c", "octave": "3" },
    step04: { "toneName": "d", "octave": "3" },
    step05: { "toneName": "d", "octave": "3" },
    step06: { "toneName": "c", "octave": "3" },
    step07: { "toneName": "c", "octave": "3" },
    step08: { "toneName": "d", "octave": "3" },
    step09: { "toneName": "d", "octave": "3" },
    step10: { "toneName": "", "octave": "3" },
    step11: { "toneName": "", "octave": "3" },
    step12: { "toneName": "f", "octave": "3" },
    step13: { "toneName": "f", "octave": "3" },
    step14: { "toneName": "", "octave": "3" },
    step15: { "toneName": "", "octave": "3" }
  },
  CoolBass: {
    step00: { "toneName": "e", "octave": "1" },
    step01: { "toneName": "e", "octave": "2" },
    step02: { "toneName": "e", "octave": "2" },
    step03: { "toneName": "e", "octave": "2" },
    step04: { "toneName": "e", "octave": "1" },
    step05: { "toneName": "e", "octave": "2" },
    step06: { "toneName": "e", "octave": "2" },
    step07: { "toneName": "e", "octave": "2" },
    step08: { "toneName": "g", "octave": "1" },
    step09: { "toneName": "g", "octave": "2" },
    step10: { "toneName": "a#", "octave": "3" },
    step11: { "toneName": "g", "octave": "3" },
    step12: { "toneName": "a", "octave": "1" },
    step13: { "toneName": "a", "octave": "2" },
    step14: { "toneName": "a", "octave": "3" },
    step15: { "toneName": "a", "octave": "2" }
  },
  Funky: {
    step00: { "toneName": "g", "octave": "1" },
    step01: { "toneName": "-->", "octave": "2" },
    step02: { "toneName": "", "octave": "2" },
    step03: { "toneName": "g", "octave": "2" },
    step04: { "toneName": "-->", "octave": "1" },
    step05: { "toneName": "", "octave": "2" },
    step06: { "toneName": "f", "octave": "2" },
    step07: { "toneName": "g", "octave": "2" },
    step08: { "toneName": "a#", "octave": "1" },
    step09: { "toneName": "-->", "octave": "2" },
    step10: { "toneName": "a#", "octave": "3" },
    step11: { "toneName": "", "octave": "3" },
    step12: { "toneName": "c", "octave": "2" },
    step13: { "toneName": "-->", "octave": "2" },
    step14: { "toneName": "c", "octave": "4" },
    step15: { "toneName": "", "octave": "2" }
  },
}